#!/usr/bin/env python3
"""Build a readable Excel BI model report from exported inspection JSON.

Inputs are intentionally JSON files generated by the companion inspectors:

- inspect_excel_data_model_com.ps1 for Power Pivot / Data Model metadata.
- inspect_excel_bi_workbook.py for report-layer workbook and CUBE formula metadata.

The script is cross-platform and never opens Excel.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from mdx_references import cube_measure_refs, member_refs


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def table_name(value: Any) -> str:
    if isinstance(value, dict):
        return str(value.get("name", ""))
    return str(value or "")


def markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    def clean(value: Any) -> str:
        text = "" if value is None else str(value)
        return text.replace("\n", "<br>").replace("|", "\\|")

    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(clean(value) for value in row) + " |")
    return lines


def extract_cube_usage(openxml: dict[str, Any] | None) -> dict[str, Any]:
    if not openxml:
        return {
            "cube_formula_count": 0,
            "measure_usage": Counter(),
            "sheet_usage": Counter(),
            "formulas_by_measure": defaultdict(list),
            "member_references": Counter(),
        }

    measure_usage: Counter[str] = Counter()
    sheet_usage: Counter[str] = Counter()
    formulas_by_measure: dict[str, list[dict[str, Any]]] = defaultdict(list)
    member_references: Counter[str] = Counter()

    cube_formulas = openxml.get("cubeFormulas", [])
    for formula_record in cube_formulas:
        formula = str(formula_record.get("formula", ""))
        sheet = str(formula_record.get("sheet", ""))
        cell = str(formula_record.get("cell", ""))
        sheet_usage[sheet] += 1

        measures = cube_measure_refs(formula)
        for measure in measures:
            measure_usage[measure] += 1
            formulas_by_measure[measure].append(
                {
                    "sheet": sheet,
                    "cell": cell,
                    "formula": formula,
                    "cachedValue": formula_record.get("cachedValue"),
                }
            )

        for ref in member_refs(formula):
            member_references[ref] += 1

    return {
        "cube_formula_count": len(cube_formulas),
        "measure_usage": measure_usage,
        "sheet_usage": sheet_usage,
        "formulas_by_measure": formulas_by_measure,
        "member_references": member_references,
    }


def build_summary_json(model: dict[str, Any], openxml: dict[str, Any] | None) -> dict[str, Any]:
    cube_usage = extract_cube_usage(openxml)
    measures = model.get("measures", [])
    measure_names = [str(item.get("name", "")) for item in measures]
    referenced = set(cube_usage["measure_usage"].keys())

    return {
        "workbookPath": model.get("workbookPath") or (openxml or {}).get("workbookPath"),
        "modelAvailable": model.get("modelAvailable"),
        "tableCount": model.get("tableCount", len(model.get("tables", []))),
        "relationshipCount": model.get("relationshipCount", len(model.get("relationships", []))),
        "measureCount": model.get("measureCount", len(measures)),
        "connectionCount": len(model.get("connections", [])),
        "cubeFormulaCount": cube_usage["cube_formula_count"],
        "tables": [
            {
                "name": item.get("name", ""),
                "sourceName": item.get("sourceName", ""),
                "recordCount": item.get("recordCount"),
                "columnCount": item.get("columnCount"),
            }
            for item in model.get("tables", [])
        ],
        "relationships": model.get("relationships", []),
        "measures": [
            {
                "name": item.get("name", ""),
                "associatedTable": table_name(item.get("associatedTable")),
                "formula": item.get("formula", ""),
                "cubeFormulaReferenceCount": cube_usage["measure_usage"].get(str(item.get("name", "")), 0),
            }
            for item in measures
        ],
        "measuresReferencedByCubeFormulas": sorted(referenced),
        "measuresNotReferencedByCubeFormulas": sorted(set(measure_names) - referenced),
        "cubeFormulaReferencesMissingModelMeasure": sorted(referenced - set(measure_names)),
        "cubeFormulaSheetUsage": dict(cube_usage["sheet_usage"].most_common()),
        "topMemberReferences": dict(cube_usage["member_references"].most_common(30)),
    }


def render_measure_formula(formula: str) -> str:
    formula = formula.strip()
    if not formula:
        return "_No formula exposed by Excel COM._"
    return f"```DAX\n{formula}\n```"


def mermaid_label(value: Any) -> str:
    return str(value or "").replace("\\", "\\\\").replace('"', '\\"')


def render_markdown(summary: dict[str, Any], model: dict[str, Any], openxml: dict[str, Any] | None) -> str:
    cube_usage = extract_cube_usage(openxml)
    lines: list[str] = [
        "# Excel BI Model Report",
        "",
        f"- workbook: `{summary.get('workbookPath', '')}`",
        f"- model available: `{summary.get('modelAvailable')}`",
        f"- model tables: {summary.get('tableCount')}",
        f"- relationships: {summary.get('relationshipCount')}",
        f"- measures: {summary.get('measureCount')}",
        f"- workbook connections: {summary.get('connectionCount')}",
        f"- CUBE formulas: {summary.get('cubeFormulaCount')}",
        "",
    ]

    tables = summary.get("tables", [])
    if tables:
        lines.extend(["## Model Tables", ""])
        lines.extend(
            markdown_table(
                ["Table", "Source", "Rows", "Columns"],
                [
                    [item.get("name"), item.get("sourceName"), item.get("recordCount"), item.get("columnCount")]
                    for item in tables
                ],
            )
        )
        lines.append("")

    relationships = summary.get("relationships", [])
    if relationships:
        lines.extend(["## Relationships", ""])
        lines.extend(
            markdown_table(
                ["Foreign Key", "Primary Key", "Active"],
                [
                    [
                        f"{item.get('foreignKeyTable', '')}[{item.get('foreignKeyColumn', '')}]",
                        f"{item.get('primaryKeyTable', '')}[{item.get('primaryKeyColumn', '')}]",
                        item.get("active"),
                    ]
                    for item in relationships
                ],
            )
        )
        lines.extend(["", "```mermaid", "graph LR"])
        for index, item in enumerate(relationships, start=1):
            left = f"fk{index}[\"{mermaid_label(item.get('foreignKeyTable', ''))}\"]"
            right = f"pk{index}[\"{mermaid_label(item.get('primaryKeyTable', ''))}\"]"
            label = mermaid_label(f"{item.get('foreignKeyColumn', '')} -> {item.get('primaryKeyColumn', '')}")
            lines.append(f"  {left} -->|\"{label}\"| {right}")
        lines.extend(["```", ""])

    measures = summary.get("measures", [])
    if measures:
        lines.extend(["## Measures", ""])
        lines.extend(
            markdown_table(
                ["Measure", "Table", "CUBE References"],
                [
                    [item.get("name"), item.get("associatedTable"), item.get("cubeFormulaReferenceCount")]
                    for item in measures
                ],
            )
        )
        lines.append("")
        for item in measures:
            lines.extend(
                [
                    f"### {item.get('name', '')}",
                    "",
                    f"- associated table: `{item.get('associatedTable', '')}`",
                    f"- CUBE formula references: {item.get('cubeFormulaReferenceCount')}",
                    "",
                    render_measure_formula(str(item.get("formula", ""))),
                    "",
                ]
            )

    if summary.get("cubeFormulaCount"):
        lines.extend(["## CUBE Formula Usage", ""])
        sheet_usage = summary.get("cubeFormulaSheetUsage", {})
        if sheet_usage:
            lines.extend(["### By Sheet", ""])
            lines.extend(markdown_table(["Sheet", "CUBE Formulas"], [[k, v] for k, v in sheet_usage.items()]))
            lines.append("")

        measure_usage = cube_usage["measure_usage"].most_common()
        if measure_usage:
            lines.extend(["### By Measure", ""])
            lines.extend(markdown_table(["Measure", "Formula Count"], measure_usage))
            lines.append("")

        missing = summary.get("cubeFormulaReferencesMissingModelMeasure", [])
        if missing:
            lines.extend(["### CUBE References Not Found In Model Measures", ""])
            for name in missing:
                lines.append(f"- `{name}`")
            lines.append("")

        unused = summary.get("measuresNotReferencedByCubeFormulas", [])
        if unused:
            lines.extend(["### Measures Not Referenced By CUBE Formulas", ""])
            for name in unused:
                lines.append(f"- `{name}`")
            lines.append("")

    lines.extend(
        [
            "## Validation Notes",
            "",
            "- This report is generated from exported metadata and does not refresh queries or evaluate formulas.",
            "- Windows desktop Excel COM is required for the Data Model export step.",
            "- OpenXML CUBE formula scanning is structural; always validate final values in Excel when changing formulas.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-json", required=True, type=Path, help="JSON from inspect_excel_data_model_com.ps1")
    parser.add_argument("--openxml-json", type=Path, help="Optional JSON from inspect_excel_bi_workbook.py")
    parser.add_argument("--out-md", type=Path, help="Write Markdown report")
    parser.add_argument("--out-json", type=Path, help="Write normalized summary JSON")
    parser.add_argument("--print", action="store_true", help="Print Markdown report to stdout")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    model = load_json(args.model_json.expanduser().resolve())
    openxml = load_json(args.openxml_json.expanduser().resolve()) if args.openxml_json else None
    summary = build_summary_json(model, openxml)
    markdown = render_markdown(summary, model, openxml)

    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Wrote summary JSON: {args.out_json}")
    if args.out_md:
        args.out_md.parent.mkdir(parents=True, exist_ok=True)
        args.out_md.write_text(markdown, encoding="utf-8")
        print(f"Wrote Markdown report: {args.out_md}")
    if args.print or (not args.out_json and not args.out_md):
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
